POST http://localhost:4800/api/login
content-type: application/json


{
    "email": "sandeepguptabc@gmail.com",
    "password": "123456"
}

###

POST http://localhost:4800/api/forgotPassword
content-type: application/json

{
    "email": "sandeepguptabc@gmail.com"
}

###
PUT  http://localhost:4800/api/resetPassword/4f73822cc23eec320db9f188a033025108652ded1e744327aa9abb68bb466ef23e2ee5
content-type: application/json

{
    "password" : "123456"
}