POST http://localhost:4800/api/login
content-type: application/json


{
    "email": "sandeepguptabc@gmail.com",
    "password": "123456"
}

###

POST http://localhost:4800/api/forgotPassword
content-type: application/json

{
    "email": "sandeepguptabc@gmail.com"
}

###
PUT  http://localhost:4800/api/resetPassword/8a222b584c01161e7e6813c496af4dcb25767a0da9b0d2da5645d33be830b49c92e3e0
content-type: application/json

{
    "password" : "123456"
}